#include "bmc/smt2_builder.h"
#include "frontend/smt2_parser.h"
#include "utils/bitvec_utils.h"
#include <sstream>

namespace symbfuzz {

namespace {

// SMT2 function name for the module's state sort, e.g. |mymod_s|
std::string sort_name(const std::string& mod)   { return "|" + mod + "_s|"; }
std::string init_fn(const std::string& mod)     { return "|" + mod + "_i|"; }
std::string trans_fn(const std::string& mod)    { return "|" + mod + "_t|"; }
std::string accessor(const std::string& mod, const std::string& wire) {
    return "|" + mod + "_n " + wire + "|";
}
std::string state_var(int step) { return "s" + std::to_string(step); }

} // namespace

std::string build_bmc_query(const DesignModel& model,
                             const TargetSpec&  target,
                             int                depth) {
    const std::string& M = model.module_name;
    std::ostringstream q;

    // ---- Logic --------------------------------------------------------
    q << "(set-logic QF_UFBV)\n\n";

    // ---- Embed the full Yosys-generated SMT2 --------------------------
    q << "; === Design model (generated by Yosys write_smt2) ===\n";
    q << model.smt2_text << "\n";
    q << "; === End of design model ===\n\n";

    // ---- Declare state variables s0 .. s{depth} -----------------------
    q << "; State variables\n";
    for (int i = 0; i <= depth; ++i)
        q << "(declare-fun " << state_var(i) << " () " << sort_name(M) << ")\n";
    q << "\n";

    // ---- Initial state ------------------------------------------------
    q << "; Initial state (mod_i constrains clock/reset samplers)\n";
    q << "(assert (" << init_fn(M) << " " << state_var(0) << "))\n";

    // Zero-initialise architectural data registers (sample_data kind).
    // mod_i already handles the sample_control / sample_control_edge registers.
    if (target.assume_zero_init) {
        q << "; Zero-initialise data registers at s0\n";
        for (const auto& reg : model.registers) {
            if (reg.kind == RegKind::SampleData) {
                std::string acc = "(" + accessor(M, reg.name) + " " + state_var(0) + ")";
                if (reg.returns_bool) {
                    // Bool accessor: use (not acc) to assert = false (= 0)
                    q << "(assert (not " << acc << "))\n";
                } else {
                    q << "(assert (= " << acc << " " << to_bv_literal(0, reg.width) << "))\n";
                }
            }
        }
    }
    q << "\n";

    // ---- Transition chain ---------------------------------------------
    q << "; Transition relation\n";
    for (int i = 0; i < depth; ++i)
        q << "(assert (" << trans_fn(M) << " " << state_var(i)
          << " " << state_var(i + 1) << "))\n";
    q << "\n";

    // ---- Goal constraints at final state ------------------------------
    q << "; Goal constraints at step " << depth << "\n";
    for (const auto& c : target.constraints) {
        std::string acc = "(" + accessor(M, c.wire_name) + " " + state_var(depth) + ")";
        std::string acc_prev;
        if (c.flip && depth >= 1)
            acc_prev = "(" + accessor(M, c.wire_name) + " "
                     + state_var(depth - 1) + ")";

        // Interpret `c.value` (hex/decimal/SMT2 literal string) as the
        // value's low bit for bit-level constraints, or as the full
        // width for full-width constraints. For Bool accessors, only
        // the LSB matters.
        // Quick low-bit extract: last hex nibble of the normalised
        // value has the LSB in its bit 0.
        auto lsb_of = [](const std::string& s) -> int {
            // Handles "0" / "1" / decimal / hex — reuse the utility.
            std::string hex = "0x" + (s.empty() ? std::string("0") : s);
            (void)hex;
            // Simpler: parse to uint64_t (safe for LSB) via existing helper.
            return static_cast<int>(parse_bv_literal(s.substr(0,2) == "#b" || s.substr(0,2) == "#x"
                                                    ? s : "#b" + std::string("0"), 1) & 1);
        };
        (void)lsb_of;   // placeholder — actual LSB fetched below
        auto lsb_from_string = [](const std::string& s) -> int {
            if (s.empty()) return 0;
            if (s == "true")  return 1;
            if (s == "false") return 0;
            // Take the last character of the value's low nibble. For
            // decimal/hex, look at the trailing character.
            char c = s.back();
            if (c >= '0' && c <= '9') return (c - '0') & 1;
            if (c >= 'a' && c <= 'f') return ((c - 'a' + 10)) & 1;
            if (c >= 'A' && c <= 'F') return ((c - 'A' + 10)) & 1;
            return 0;
        };

        if (c.returns_bool) {
            // 1-bit Bool accessor: assert true/false directly at step k, and
            // — if flip is requested — the opposite at step k-1.
            int lsb = lsb_from_string(c.value);
            std::string cur = (lsb ? acc : "(not " + acc + ")");
            if (c.flip && depth >= 1) {
                std::string prev = (lsb ? "(not " + acc_prev + ")"
                                        : acc_prev);
                q << "(assert (and " << cur << " " << prev << "))\n";
            } else {
                q << "(assert " << cur << ")\n";
            }
        } else if (c.bit >= 0) {
            // Bit-extract equality. Constant form is `(_ bv<value> <width>)`.
            unsigned long long v_cur = lsb_from_string(c.value) & 1ULL;
            std::string ext_cur = "((_ extract " + std::to_string(c.bit) + " "
                                + std::to_string(c.bit) + ") " + acc + ")";
            if (c.flip && depth >= 1) {
                unsigned long long v_prev = v_cur ^ 1ULL;
                std::string ext_prev = "((_ extract " + std::to_string(c.bit) + " "
                                     + std::to_string(c.bit) + ") " + acc_prev + ")";
                q << "(assert (and "
                  << "(= " << ext_cur  << " (_ bv" << v_cur  << " 1)) "
                  << "(= " << ext_prev << " (_ bv" << v_prev << " 1))"
                  << "))\n";
            } else {
                q << "(assert (= " << ext_cur << " (_ bv" << v_cur << " 1)))\n";
            }
        } else {
            // Full-width equality — width is not bounded by uint64,
            // so we route through the hex-string SMT2 literal builder.
            q << "(assert (= " << acc << " " << to_bv_literal_from_hex(c.value, c.width) << "))\n";
        }
    }
    q << "\n";

    // ---- Check-sat ----------------------------------------------------
    q << "(check-sat)\n\n";

    // ---- get-value for all inputs at each step ------------------------
    q << "; Witness: input values at each step\n";
    q << "(get-value (";
    bool first = true;
    for (int i = 0; i < depth; ++i) {          // step 0 .. depth-1 are the inputs
        for (const auto& port : model.inputs) {
            if (!first) q << "\n             ";
            first = false;
            q << "(" << accessor(M, port.name) << " " << state_var(i) << ")";
        }
    }
    q << "))\n";

    return q.str();
}

} // namespace symbfuzz
