#include "bmc/smt2_builder.h"
#include "frontend/smt2_parser.h"
#include "utils/bitvec_utils.h"
#include <sstream>

namespace symbfuzz {

namespace {

// SMT2 function name for the module's state sort, e.g. |mymod_s|
std::string sort_name(const std::string& mod)   { return "|" + mod + "_s|"; }
std::string init_fn(const std::string& mod)     { return "|" + mod + "_i|"; }
std::string trans_fn(const std::string& mod)    { return "|" + mod + "_t|"; }
std::string accessor(const std::string& mod, const std::string& wire) {
    return "|" + mod + "_n " + wire + "|";
}
std::string state_var(int step) { return "s" + std::to_string(step); }

} // namespace

std::string build_bmc_query(const DesignModel& model,
                             const TargetSpec&  target,
                             int                depth) {
    const std::string& M = model.module_name;
    std::ostringstream q;

    // ---- Logic --------------------------------------------------------
    q << "(set-logic QF_UFBV)\n\n";

    // ---- Embed the full Yosys-generated SMT2 --------------------------
    q << "; === Design model (generated by Yosys write_smt2) ===\n";
    q << model.smt2_text << "\n";
    q << "; === End of design model ===\n\n";

    // ---- Declare state variables s0 .. s{depth} -----------------------
    q << "; State variables\n";
    for (int i = 0; i <= depth; ++i)
        q << "(declare-fun " << state_var(i) << " () " << sort_name(M) << ")\n";
    q << "\n";

    // ---- Initial state ------------------------------------------------
    q << "; Initial state (mod_i constrains clock/reset samplers)\n";
    q << "(assert (" << init_fn(M) << " " << state_var(0) << "))\n";

    // Zero-initialise architectural data registers (sample_data kind).
    // mod_i already handles the sample_control / sample_control_edge registers.
    if (target.assume_zero_init) {
        q << "; Zero-initialise data registers at s0\n";
        for (const auto& reg : model.registers) {
            if (reg.kind == RegKind::SampleData) {
                std::string acc = "(" + accessor(M, reg.name) + " " + state_var(0) + ")";
                if (reg.returns_bool) {
                    // Bool accessor: use (not acc) to assert = false (= 0)
                    q << "(assert (not " << acc << "))\n";
                } else {
                    q << "(assert (= " << acc << " " << to_bv_literal(0, reg.width) << "))\n";
                }
            }
        }
    }
    q << "\n";

    // ---- Transition chain ---------------------------------------------
    q << "; Transition relation\n";
    for (int i = 0; i < depth; ++i)
        q << "(assert (" << trans_fn(M) << " " << state_var(i)
          << " " << state_var(i + 1) << "))\n";
    q << "\n";

    // ---- Goal constraints at final state ------------------------------
    q << "; Goal constraints at step " << depth << "\n";
    for (const auto& c : target.constraints) {
        std::string acc = "(" + accessor(M, c.wire_name) + " " + state_var(depth) + ")";
        if (c.returns_bool) {
            // Bool accessor: assert true (value != 0) or false (value == 0)
            q << "(assert " << (c.value ? acc : "(not " + acc + ")") << ")\n";
        } else {
            q << "(assert (= " << acc << " " << to_bv_literal(c.value, c.width) << "))\n";
        }
    }
    q << "\n";

    // ---- Check-sat ----------------------------------------------------
    q << "(check-sat)\n\n";

    // ---- get-value for all inputs at each step ------------------------
    q << "; Witness: input values at each step\n";
    q << "(get-value (";
    bool first = true;
    for (int i = 0; i < depth; ++i) {          // step 0 .. depth-1 are the inputs
        for (const auto& port : model.inputs) {
            if (!first) q << "\n             ";
            first = false;
            q << "(" << accessor(M, port.name) << " " << state_var(i) << ")";
        }
    }
    q << "))\n";

    return q.str();
}

} // namespace symbfuzz
