"""
drivers/verilator.py — Verilator backend.

Spawns the Verilator-compiled simulation executable and communicates via the
shared JSON-over-stdio protocol (see drivers/base.py). The C++ harness is
generated by :func:`symfuzz.testbench_gen.generate_verilator_harness` and
compiled by the generated ``compile_<module>.sh`` script.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Optional

from .base import BaseStdioDriver, CoverageSnapshot


class VerilatorDriver(BaseStdioDriver):
    backend_name = "verilator"

    # Coverage-universe hierarchy patterns to exclude. Useful for
    # wrapper-based fuzz setups where the wrapper introduces aliased
    # struct repackaging signals that inflate the bin count. Set via
    # VerilatorDriver.coverage_exclude_hier (list of fnmatch patterns).
    coverage_exclude_hier: list[str] = []

    def collect_coverage(self) -> Optional[CoverageSnapshot]:
        resp = self._send({"cmd": "coverage"})
        if "error" in resp:
            if self.verbose:
                print(f"[verilator] coverage error: {resp['error']}")
            return None
        report = resp.get("report", "")
        if not report:
            return None
        top = getattr(self.design, "module_name", None)
        return _parse_verilator_cov_dat(
            report, top_module=top,
            exclude_hier=self.coverage_exclude_hier,
        )

    @staticmethod
    def _check_installed() -> str:
        """Return the verilator binary path or raise a clear error."""
        path = shutil.which("verilator")
        if path is None:
            raise RuntimeError(
                "verilator not found on PATH. "
                "Install Verilator ≥ 5.0 (e.g. 'sudo apt install verilator')."
            )
        return path

    @property
    def _vtb_dir(self) -> Path:
        return self.tb_dir / "verilator"

    @property
    def _executable(self) -> Path:
        return self._vtb_dir / "obj_dir" / f"{self.design.module_name}_sim"

    def compile(self) -> None:
        self._check_installed()
        script = self._vtb_dir / f"compile_{self.design.module_name}.sh"
        if not script.exists():
            raise RuntimeError(
                f"verilator compile script not found: {script}. "
                f"Did generate_verilator_harness run?"
            )
        if self.verbose:
            print("[symfuzz] Compiling with Verilator ...")
        result = subprocess.run(
            ["bash", str(script)],
            cwd=str(self._vtb_dir),
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"verilator compile failed:\n{result.stdout}\n{result.stderr}"
            )
        if self.verbose:
            print(result.stdout.strip())

    # ------------------------------------------------------------------ #
    # Subprocess lifecycle                                                 #
    # ------------------------------------------------------------------ #

    def load(self) -> None:
        exe = self._executable
        if not exe.exists():
            raise RuntimeError(
                f"Verilator snapshot not found: {exe}. Call compile() first."
            )
        if self.verbose:
            print(f"[symfuzz] Starting verilator {exe.name} ...")
        self._proc = subprocess.Popen(
            [str(exe)],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True, bufsize=1,
            cwd=str(self._vtb_dir),
        )


# ---------------------------------------------------------------------- #
# Verilator cov.dat parser                                                 #
# ---------------------------------------------------------------------- #

# Verilator 5.x coverage dump lines look like:
#   C '\x01f\x02<file>\x01l\x02<line>\x01n\x02<col>\x01page\x02<page>\x01o\x02<obj>\x01h\x02<hier>' <count>
#
# Each entry is a sequence of \x01<key>\x02<value> segments. Keys can be
# multi-character (e.g. "page"). The prior parser matched single-char keys
# only and captured the wrong values. Correct form: key = non-\x02 run
# following \x01, value = non-\x01 run following \x02.
#
# Known keys:
#   f    - source file path
#   l    - line number (start)
#   n    - column number
#   page - coverage category: v_branch, v_toggle, v_line, v_user
#   o    - object: "if"/"else"/"elsif"/"block" (branch/line),
#          "<signal>" or "<signal>[<bit>]" (toggle), cover-property name (user)
#   S    - optional extra start line
#   h    - hierarchy (e.g. TOP.counter)

_FIELD_RE = re.compile(r"\x01([^\x02]+)\x02([^\x01]*)")
_COV_LINE_RE = re.compile(r"^C '([^']*)'\s+(\d+)\s*$", re.MULTILINE)


# Verilator's `o` field for toggle bins has three shapes we care about:
#   `<sig>[<bit>]`               — old (pre-5.x) multi-bit format
#   `<sig>[<bit>]:0->1|1->0`     — new (5.x) multi-bit with direction
#   `<sig>:0->1|1->0`            — new (5.x) 1-bit signal with direction
# The `[bit]` group is optional — without it, bit defaults to 0. The direction
# capture (third group) lets us emit one PID per direction instead of
# double-counting rise+fall on the old aggregate format.
_OBJ_BIT_RE = re.compile(r"^(\w[\w$.]*?)(?:\[(\d+)\])?(?::(0->1|1->0))?$")


def _fully_qualified(hier: str, sig: str, top_module: str | None) -> str:
    """Build a dotted arch_name matching Yosys's flattened register names.

    Verilator's `hier` field starts with "TOP" and includes the top-module
    instance level, e.g. "TOP.serdiv.gen_lzc". Yosys's flattened
    `register.arch_name` is either bare ("state_q") for top-level flops or
    dotted ("u_inst.count") for submodule flops — with the top module name
    stripped.
    """
    parts = hier.split(".") if hier else []
    while parts and (parts[0] == "TOP" or parts[0] == top_module):
        parts.pop(0)
    return ".".join(parts + [sig]) if parts else sig


def _parse_verilator_cov_dat(text: str,
                             top_module: str | None = None,
                             exclude_hier: list[str] | None = None,
                             ) -> CoverageSnapshot:
    import fnmatch
    excl = list(exclude_hier or [])
    snap = CoverageSnapshot()
    total = 0
    for m in _COV_LINE_RE.finditer(text):
        fields_blob = m.group(1)
        hits = int(m.group(2))
        fields = {k: v for k, v in _FIELD_RE.findall(fields_blob)}
        # "page" is "v_branch/<hier>" / "v_toggle/<hier>" / etc. Strip the
        # hierarchy suffix; we already carry hierarchy separately via "h".
        page_raw = fields.get("page", "")
        page = page_raw.split("/", 1)[0]
        f    = fields.get("f", "?")
        l    = fields.get("l", "?")
        o    = fields.get("o", "?")
        h    = fields.get("h", "?")

        # Config-aware filter: drop bins whose hierarchy matches a user
        # exclude pattern (fnmatch). Used to strip wrapper-introduced
        # aliased signals and dead-config paths from the universe.
        if excl and any(fnmatch.fnmatch(h, p) for p in excl):
            continue

        if page == "v_toggle":
            # Parse the `o` field. Three cases:
            #  "name[bit]"              → split sig/bit, emit both rise+fall
            #  "name[bit]:0->1"         → split sig/bit/rise, one PID only
            #  "name[bit]:1->0"         → split sig/bit/fall, one PID only
            #  anything else            → aggregate; bit=0, both directions.
            m2 = _OBJ_BIT_RE.match(o)
            if m2:
                sig_raw = m2.group(1)
                # `[bit]` group is optional in the regex; default to 0
                # when absent (as it is for 1-bit signals).
                bit = int(m2.group(2)) if m2.group(2) is not None else 0
                dir_suffix = m2.group(3)
            else:
                sig_raw, bit = o, 0
                dir_suffix = None
            reg_fq = _fully_qualified(h, sig_raw, top_module)

            if dir_suffix == "0->1":
                dirs = (("rise", 1),)
            elif dir_suffix == "1->0":
                dirs = (("fall", 0),)
            else:
                # Old Verilator schema: aggregate hit count covers both edges.
                dirs = (("rise", 1), ("fall", 0))

            for direction, val in dirs:
                pid = f"xtgl:{h}:{sig_raw}:{bit}:{direction}"
                snap.universe.add(pid)
                snap.kinds[pid] = "toggle"
                snap.details[pid] = {
                    "page":   page, "file":   f,     "line":  l,
                    "object": o,    "hier":   h,
                    "reg":    reg_fq,
                    "bit":    bit,
                    "dir":    direction,
                }
                if hits > 0:
                    snap.points.add(pid)
                total += 1
            continue

        if page == "v_branch":
            pid  = f"branch:{f}:{l}:{o}"
            kind = "branch"
        elif page == "v_line":
            pid  = f"line:{f}:{l}:{o}"
            kind = "line"
        elif page == "v_user":
            pid  = f"user:{h}:{o}"
            kind = "user"
        else:
            pid  = f"{page or 'cov'}:{f}:{l}:{o}"
            kind = page or "unknown"

        snap.universe.add(pid)
        snap.kinds[pid] = kind
        snap.details[pid] = {
            "page":   page, "file":   f,     "line":  l,
            "object": o,    "hier":   h,
        }
        if hits > 0:
            snap.points.add(pid)
        total += 1

    snap.total = total or None
    return snap
