#include "frontend/smt2_parser.h"
#include <sstream>
#include <stdexcept>
#include <unordered_map>

namespace symbfuzz {

namespace {

bool starts_with(const std::string& s, const std::string& prefix) {
    return s.size() >= prefix.size() && s.compare(0, prefix.size(), prefix) == 0;
}

// Scan define-fun lines to build a map:  accessor-name → returns_bool
// Yosys emits accessor functions like:
//   (define-fun |mod_n signame| ((state |mod_s|)) Bool ...)     ← 1-bit Bool
//   (define-fun |mod_n signame| ((state |mod_s|)) (_ BitVec N) ...)
std::unordered_map<std::string, bool> build_return_type_map(
        const std::string& smt2_text,
        const std::string& module_name) {

    std::unordered_map<std::string, bool> result;
    const std::string prefix = "(define-fun |" + module_name + "_n ";

    std::istringstream stream(smt2_text);
    std::string line;
    while (std::getline(stream, line)) {
        if (!starts_with(line, prefix)) continue;

        // Extract signal name: between "|mod_n " and "|"
        size_t name_start = prefix.size();
        size_t name_end   = line.find('|', name_start);
        if (name_end == std::string::npos) continue;
        std::string sig_name = line.substr(name_start, name_end - name_start);

        // The return type appears after "((state |mod_s|)) " — look for "Bool" vs "(_ BitVec"
        size_t paren_close = line.find(")) ", name_end);
        if (paren_close == std::string::npos) continue;
        std::string ret_part = line.substr(paren_close + 3);

        bool is_bool = starts_with(ret_part, "Bool");
        result[sig_name] = is_bool;
    }
    return result;
}

DesignModel parse_design_model_impl(const std::string& smt2_text) {
    DesignModel model;
    model.smt2_text = smt2_text;

    // First pass: collect annotation comments
    std::istringstream stream(smt2_text);
    std::string line;

    while (std::getline(stream, line)) {
        if (!starts_with(line, "; yosys-smt2-")) continue;

        std::istringstream ls(line.substr(2)); // skip "; "
        std::string tag, name;
        ls >> tag >> name;

        if (tag == "yosys-smt2-module") {
            model.module_name = name;
        } else if (tag == "yosys-smt2-input") {
            int w = 1; ls >> w;
            model.inputs.push_back({name, w, PortDir::Input});
        } else if (tag == "yosys-smt2-output") {
            int w = 1; ls >> w;
            model.outputs.push_back({name, w, PortDir::Output});
        } else if (tag == "yosys-smt2-register") {
            int w = 1; ls >> w;
            RegKind kind = RegKind::Architectural;
            std::string arch_name;
            if (name.find("sample_data") != std::string::npos) {
                kind = RegKind::SampleData;
                auto slash = name.rfind('/');
                auto hash  = name.rfind("#sampled");
                if (slash != std::string::npos && hash != std::string::npos && hash > slash)
                    arch_name = name.substr(slash + 1, hash - slash - 1);
            } else if (name.find("sample_control") != std::string::npos) {
                kind = RegKind::SampleControl;
            } else if (name.rfind("$auto$", 0) == 0 || name.rfind("$", 0) == 0) {
                kind = RegKind::SampleControl;
            }
            model.registers.push_back({name, arch_name, w, kind, false});
        } else if (tag == "yosys-smt2-wire") {
            int w = 1; ls >> w;
            model.wires.push_back({name, w});
        }
    }

    if (model.module_name.empty())
        throw std::runtime_error("SMT2 has no yosys-smt2-module annotation. "
                                 "Was it generated by Yosys write_smt2?");

    // Second pass: determine Bool vs BitVec return type for each register's accessor
    auto type_map = build_return_type_map(smt2_text, model.module_name);
    for (auto& reg : model.registers) {
        auto it = type_map.find(reg.name);
        if (it != type_map.end())
            reg.returns_bool = it->second;
        else
            reg.returns_bool = (reg.width == 1); // fallback heuristic
    }

    return model;
}

} // namespace

DesignModel parse_design_model(const std::string& smt2_text) {
    return parse_design_model_impl(smt2_text);
}

} // namespace symbfuzz
